# Generated by Django 5.2.4 on 2025-07-27 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_product_reservation_timeout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения пользователя'), ('CONFIRMED', 'Подтверждена'), ('CANCELED', 'Отменена')], default='PENDING', max_length=30, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='goods.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='booking_boo_status_e01616_idx'), models.Index(fields=['created_at'], name='booking_boo_created_274495_idx'), models.Index(fields=['user'], name='booking_boo_user_id_d9826d_idx'), models.Index(fields=['product'], name='booking_boo_product_dca17c_idx'), models.Index(fields=['product', 'status'], name='booking_boo_product_6ab1b8_idx')],
            },
        ),
    ]
