# Generated by Django 5.2.4 on 2025-07-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reservation_timeout',
            field=models.PositiveIntegerField(default=15, help_text='Сколько минут может существовать бронь'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='goods_produ_name_bb6443_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='goods_produ_created_6a94fa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='goods_produ_price_4b4a3a_idx'),
        ),
    ]
